# Generated by Django 4.1.7 on 2023-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_movie_theater_showtime_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="image",
        ),
        migrations.AddField(
            model_name="movie",
            name="image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
