# Generated by Django 4.1.7 on 2023-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_movie_image_movie_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
