# Generated by Django 4.1.7 on 2023-02-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_movie_price_alter_movie_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="movie",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.movie"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
