# Generated by Django 4.1.7 on 2023-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_booking_movie_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
