# Generated by Django 4.1.7 on 2023-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_eventbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="price",
            field=models.IntegerField(default=10),
        ),
    ]
