# Generated by Django 3.1.12 on 2023-03-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
