# Generated by Django 3.1.12 on 2023-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
