# Generated by Django 3.1.12 on 2023-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_eventbooking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
